### ISSUE TITLE
Sessions not supported

### ISSUE THREAD

**Issue by pleeja** [FaserF/hassio-addons#11]
Hi, Love this Addon!

I want to use sessions though but session_start(); throws error because its not supported,

Is there a way to enable this or alter php.ini?

I'm new to this so sorry if I'm asking a stupid question

**Comment by FaserF** [comment]
Hi, thank you for your feedback and of course this is no stupid question :) 
I have added the option to use a custom php.ini to this addon in the new version 1.3.0

Please update the addon and give it a try. For instructions have a look here:
https://github.com/FaserF/hassio-addons/tree/master/apache2#option-php_ini

**Comment by pleeja** [comment]
Thank you so much! I've used a custom php.ini and referred to it in config but phpinfo() is still telling its using the standard file. Is this a problem with phpinfo()?

Loaded Configuration File | /etc/php7/php.ini

Also, is session_start() working for you?

**Comment by FaserF** [comment]
Can you tell me what the log output of the addon is saying?
It should say something like: "Your custom php.ini at yourLocationOfTheNewFile will be used."

Unfortunatly I am using the default php settings, so I cant tell you if it's working or not.

**Comment by pleeja** [comment]
The log says that so I guess it works

**Comment by FaserF** [comment]
Theoreticly it should work. If it still doesnt be sure to let me know if there is a issue with the custom php.ini import.

**Comment by pleeja** [comment]
Well I think the custom php.ini import works but the reason I opened the issue is because session_start() doesn't work and I don't know why. Is it disabled by default?

**Comment by FaserF** [comment]
I am sorry, but I am not working with php sessions on my private page.
I've done a quick search in google and it seems that it should work with the default settings.

**Comment by pleeja** [comment]
Okay, thanks anyway!
