### ISSUE TITLE
PHP undefined function session_start()

### ISSUE THREAD

**Issue by Hunt3rCZ** [FaserF/hassio-addons#112]
### The problem

Hello i installed your addon "Apache2 Minimal with MariaDB Client" and when i want to run  php file i got errror
But simply php page with phpinfo workfine.  

MariaDB server plug-in installed
phpmyadmin plug-in instaled
both working correctly

yaml conf is in default
document_root: /share/htdocs
php_ini: default
default_conf: default
default_ssl_conf: default
website_name: phpapi
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem

please tell me where is problem.
because have problem with run php i didnt tested mysqli connect to DB.
Is a nessecery any special config for DB connect?

part of php script is in the Additional information

Thnx

### What version of Home Assistant Core has the issue?

Supervisor 2023.01.dev1301

### What version of the addon has the issue?

latest - today installed from repository

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2 Minimal with MariaDB

### Log information

```txt
[Tue Jan 17 21:23:39.779871 2023] [php:error] [pid 146] [client xxx.xxx.xxx.xxx:63337] PHP Fatal error:  Uncaught Error: Call to undefined function session_start() in /share/htdocs/test.php:28\nStack trace:\n#0 {main}\n  thrown in /share/htdocs/test.php on line 28
```

### Additional information

<?php

session_start();

error_reporting (E_ALL ^ E_NOTICE);

$link = mysqli_connect("localhost", "user", "password" , "database");
mysqli_query($link, "SET NAMES utf8") or die("Unable to connect to MySQL: ". mysqli_error());

**Comment by FaserF** [comment]
For what I can see there should not be any issue with this addon.
You will need to specify your database login credentials within your PHP code. In my website I am using a connect_db.php which contains all the needed credentials:
```
<?php
$servername = "core-mariadb";
$dbname = "myDBname";
$username = "myUsernameSpecifiedInTheMariaDBAddon";
$password = "myPasswordSpecifiedInTheMariaDBAddon";
$db = new mysqli($servername,$username,$password,$dbname);
?>
```

then you will need to call it within your PHP code.

**Comment by FaserF** [comment]
PHP session is only supported in the apache2 full Addon. This feature is missing in the minimal Addon. So please give it another try with the full Addon

**Comment by Hunt3rCZ** [comment]
thnx, installed apache2 full Addon and now php working. Many thnx for help
