### ISSUE TITLE
httpd path

### ISSUE THREAD

**Issue by wattsjus** [FaserF/hassio-addons#114]
I cannot seem to get this project to server any file but the default.  I have used the configured path, I have searched for all htdocs folders on my system and I've never found the default index.html file.  I can tell by the logs that the folder is found or not found depending on if I have it created or not, but every time the default index.html is used, but I cannot find that location.  What is the default path that is used when first installing?  I see it should be /share/htdocs but is there another way to access that path because lets say this server is using a virtual file system?

**Comment by wattsjus** [comment]
I have my instance installed with a raspberry pi 4 on the hassio os.

**Comment by FaserF** [comment]
If you are running hassio on your raspberry pi 4, you will only need to connect to the pi and put your web files anywhere to the /share/ folder.
Then change/define the path you have put your web files at the „document_root“ configuration option:

https://github.com/FaserF/hassio-addons/tree/master/apache2#option-document_root

**Comment by wattsjus** [comment]
I've changed the document root to match where my files are on the host and I have the same results.

Home Assistant 2023.1.6
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

I can copy my pem files to the /config/ssl folder because that is where I have them for other projects, yet the files cannot be found.  I've copied the add-on as a local add-on and I am still having issues finding files on the host os.  What is odd is if the folder doesn't exist it says it cannot find the folder.  If I have the folder with files in them then it says "You haven't put your website to /share/htdocs" and will only serve the default index.html, yet I cannot find this index.html on my host os.

I searched for every htdocs folder on my host os and put an index.html in all of them.  The best reasoning is that this add-on is still loading the docker image and I want it to run on the host os.

**Comment by wattsjus** [comment]
okay!  That worked, I read a little closer to what you wrote.  I put an index.html in the root /share folder and the default index.html wasn't loaded, but it also said that there were no files.  So then I put another index.html in the htdocs folder and my files are read.  The index.html on the root doesn't seem to do anything as it's not served, but at the least it is working now.

**Comment by wattsjus** [comment]
No I was able to one time get a php file to execute, so that is awesome.  I'm trying to serve a html page and every time the page is blank.  I see my requests coming through but I'm not getting any output even after renaming the html page have a php extension.

172.30.32.1 - - [21/Jan/2023:11:31:05 -0600] "GET /index.html HTTP/1.1" 200 4363
172.30.32.1 - - [21/Jan/2023:11:32:46 -0600] "GET /index.php HTTP/1.1" 200 4363
172.30.32.1 - - [21/Jan/2023:11:32:52 -0600] "GET /index.php HTTP/1.1" 200 4363

**Comment by FaserF** [comment]
And you are using the full apache2 Addon?

most likely this is a issue with the php page itself or a php extension is missing

**Comment by wattsjus** [comment]
yes I am using the full apache2 add-on.
Apache2 
Current version: 2.5.0 (Changelog)

currently both an html page and php pages are blank, the page I have is just html.  As far as I can tell there are no errors or components missing.

**Comment by wattsjus** [comment]
I'm thinking some of it has to do with caching in this case.  I have changed the file and it's holding on to the previous version.
