### ISSUE TITLE
Repo Not becoming visible ? 

### ISSUE THREAD

**Issue by Tontze** [FaserF/hassio-addons#122]
### The problem

Just added this repo via link, doesnt seem to become visible in hass os ? 

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.3

### What version of the addon has the issue?

latest

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

### Log information

```txt
nothing to log
```

### Additional information

-

**Comment by FaserF** [comment]
Please double check that you have added:
https://github.com/FaserF/hassio-addons

Without any sub directory.
Also remove it again, add it again and do a full Homeassistant restart and then check again if it still is not available

**Comment by Tontze** [comment]
Nope, didnt help :/

**Comment by Tontze** [comment]
Hm, okay. Suddenly it became visible so not problem anymore. I dont know what was going on.
