### ISSUE TITLE
[Feature Request]: Option to add extra packages at start

### ISSUE THREAD

**Issue by codyrocco** [FaserF/hassio-addons#124]
### The request

Having some Perl modules required to be loaded, in order for my site apps to run, it will be nice to have an option to install them at addon start, using the configuration page (right now i do this with an automation)

### For which Add-On

Apache2

**Comment by FaserF** [comment]
Sadly this is not possible. I can only deploy options to select after the base operating system with all modules are already installed. If you tell me the module I can add it to the full version.

**Comment by codyrocco** [comment]
Perl packages are a bit difficult to build from CPAN, because a lot of dev tools are missing, fortunately alpine  packages are pre-built. 

Right now I use a script, triggered  by apache2 binary sensor:

/usr/bin/docker exec -i addon_605cee21_apache2 /sbin/apk add inetutils-telnet perl-dbi perl-dbd-mysql perl-cgi

Is working, but the binary sensor toggles with great delay, some 5 minutes after add-on start. 

⁣Maybe something like SSH add-on is doing (community one) could be implemented, installing other packages every start. If not, isn't such a problem, my (inelegant) solution is doing the job, and I could add any other package there. 

Codruț C. Răcoșanu

**Comment by FaserF** [comment]
you can now give it a try with the new version 2.6.0

**Comment by codyrocco** [comment]
2.6.0 will not start, unless init_command specified
