### ISSUE TITLE
[Bug]: Apache2 doesn't install

### ISSUE THREAD

**Issue by remyscherer** [FaserF/hassio-addons#127]
### The problem

Hello FaserF,

I have had an issue when changing the config and I broke something I guess. 
I had tried to change the default_conf to enable my .htaccess file, when the apache wouldn't let me restart it. I changed the default_conf back to the default setting and it still did not restart. I made a save copy of all my files & tried to uninstall and reinstall it, but now it throws an error, when I try to install it again.

Here are some log files, I hope this is just a minor thing or something that I can fix on my side maybe..? 

Running on a proxmox server

### What version of Home Assistant Core has the issue?

2023.2.5

### What version of the addon has the issue?

I guess the newest

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

### Log information

```txt
23-02-20 09:36:39 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for 605cee21/amd64-addon-apache2:2.5.0
23-02-20 09:36:50 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build 605cee21/amd64-addon-apache2:2.5.0: The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php81-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6
23-02-20 09:36:50 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/22 : ARG BUILD_FROM=ghcr.io/hassio-addons/base:13.1.0
Step 2/22 : FROM ${BUILD_FROM}
 ---> eb8315f819a1
Step 3/22 : RUN mkdir /run/apache2
 ---> Using cache
 ---> 5c007b1dbf2a
Step 4/22 : RUN apk --no-cache add apache2 php81-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl
 ---> Running in 0d8f77f81e2e
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: temporary error (try again later)
```

### Additional information

Is there some docker command that I can execute?

**Comment by FaserF** [comment]
Hi, looks to me that this is no issue with your config file at all. Maybe a temporary network issue or a general DNS issue like in #33 

Does installing any other Addon work? Can you give it another try now since some days moved on? 
Nevertheless I have updated the addon to use a newer base image, which also could fix the alpine 3.16 download error (as it now is using alpine 3.17

**Comment by remyscherer** [comment]
Hi FaserF,

thanks for the effort. Unfortunately the exact same error message for version 2.6.0 (and after restart). I uninstalled AdGuard Home and installed it back, no errors there. 

Here the update from all 3 Apache2 Modules:

**Apache2:**
The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php81-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6

**Apache Minimal:**
The command '/bin/ash -o pipefail -c apk --no-cache add apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 5

**Apache2 Minimal MariaDB:**
The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php81-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6

**My About**
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

I was running it already for a long time (like easily 6 months, 5 months on a Pi3 and now on a fujitsu with proxmox), but that worked also for like a month without any issues...

**Comment by FaserF** [comment]
Yes, this definitly sounds like #33 where I have no fix available, as it looks like a local DNS issue. 
Could you change the local DNS provider (in your adguard) to a different one and give it another try?
You could also try a ping to https://dl-cdn.alpinelinux.org on your Homeassistant OS host

**Comment by remyscherer** [comment]
Hello FaserF,

I tried to run the command that returns the error directly in the SSH Terminal Addon. 
![Home-Assistant](https://user-images.githubusercontent.com/27846555/223844575-83a796bc-0c1d-4906-97ca-6afcdbda921e.png)

Is this something that helps you? 
![Home-Assistant (1)](https://user-images.githubusercontent.com/27846555/223844801-05371433-ae57-48dd-bc80-41ec0b868e30.png)

Looks for me like no DNS errors or something similar...

**Comment by remyscherer** [comment]
I found "the" solution! 
My network settings where set on DHCP! Changed to static IP with static DNS and now it works again!

https://community.home-assistant.io/t/errors-when-buliding-a-new-addon/198841/13

**Comment by FaserF** [comment]
Great to hear! Thanks for the feedback
