### ISSUE TITLE
[Bug]: Freenom-DNS-Updater can't read my config file

### ISSUE THREAD

**Issue by blackie333** [FaserF/hassio-addons#128]
### The problem

Hello, I want to use your Freenom-DNS-Updater HA Add-On for renewal of my 3 freenom registered domains. 
After HA add-on installation today I prepared my config file according to maxisoft/Freenom-dns-updater example and put to my HA server as /share/freenom.yaml
![image](https://user-images.githubusercontent.com/22171229/221351403-b40970dd-311a-40f5-a2ea-8e1ede391019.png)

Add-on configuration is simple:
![image](https://user-images.githubusercontent.com/22171229/221351040-85aeb4af-cc3c-4fbd-95ec-45f0f88ef27e.png)

![image](https://user-images.githubusercontent.com/22171229/221351508-3efdc7af-aa44-44c5-8a23-b9aa43944221.png)

Can't find out where am I doing mistake, any advice is really appreciated.

### What version of Home Assistant Core has the issue?

2023.2.5

### What version of the addon has the issue?

Current version: 1.2.2

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Freenom-DNS-Updater

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
parse error: Expected string key before ':' at line 1, column 4
[09:30:36] ERROR: Unknown HTTP error occured
Seems there is no config file at null
Check the path again. Exiting script now
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

My HomeAssistant is based on HAOS installation using HTTPS via "Nginx Proxy Manager" Add-On.
Home Assistant 2023.2.5 
Supervisor 2023.01.1 
Operating System 9.5 
Frontend 20230202.0 - latest

**Comment by FaserF** [comment]
Thanks for the feedback. Fixed with the newest version 1.2.3

**Comment by blackie333** [comment]
Thanks a lot for ultra fast fixing and releasing the new version :)

It's seems to be working now, my domains renewal period (14 days) starts tomorrow so I will check again.
There are some warnings in the log, not sure whether it's normal so I copy the log output just FYI:

/usr/lib/python3.10/site-packages/freenom_dns_updater/encrypted_string.py:28: UserWarning: Using default key is not secure at all
  warnings.warn("Using default key is not secure at all")
Error while updating: can't parse the given html
No record updated
Starting FDU every 86400 with the config file /share/freenom.yaml
/usr/lib/python3.10/site-packages/freenom_dns_updater/encrypted_string.py:28: UserWarning: Using default key is not secure at all
  warnings.warn("Using default key is not secure at all")
/usr/lib/python3.10/site-packages/freenom_dns_updater/scripts/fdu.py:298: UserWarning: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/freenom_dns_updater/scripts/fdu.py", line 294, in record_action
    action(freenom, rec)
  File "/usr/lib/python3.10/site-packages/freenom_dns_updater/scripts/fdu.py", line 208, in <lambda>
    ok_count, err_count = record_action(lambda freenom, rec: freenom.add_record(rec, True), config, ignore_errors)
  File "/usr/lib/python3.10/site-packages/freenom_dns_updater/freenom.py", line 67, in add_record
    records = self.list_records(record.domain)
  File "/usr/lib/python3.10/site-packages/freenom_dns_updater/freenom.py", line 60, in list_records
    ret = RecordParser.parse(r.text)
  File "/usr/lib/python3.10/site-packages/freenom_dns_updater/record_parser.py", line 14, in parse
    raise ValueError("can't parse the given html")
ValueError: can't parse the given html
  warnings.warn(traceback.format_exc())
Updated 0 record
No record updated
/usr/lib/python3.10/site-packages/freenom_dns_updater/encrypted_string.py:28: UserWarning: Using default key is not secure at all
  warnings.warn("Using default key is not secure at all")
Successfully Updated 3 domains

**Comment by FaserF** [comment]
Yes this is "normal" :) and comes from the program https://github.com/maxisoft/Freenom-dns-updater

**Comment by blackie333** [comment]
Renewal period (14 days) for my domains just started today so I wanted to check whether it's working...

Unfortunately my domains have not been renewed yet, run it 4 times today but still no domain renewed.
![image](https://user-images.githubusercontent.com/22171229/221426931-ba03c904-249c-4740-b323-e1d4bd411a0e.png)
I can click on "Renew This Domain" button manually where I must choose a period (1-12 months).
![image](https://user-images.githubusercontent.com/22171229/221427218-aa086ea7-0df2-4c8d-a6ac-6fcc427068eb.png)

There is no renewal period setting in the maxisoft config file.
Not sure is this could be the problem reason. The log is exactly the same like yesterday.

I have a static IP so I don't need to update DNS records, only to renew my 3 domains every 12 months...
I want to assign this important task to some automation without memory issues like me :)
Would be very grateful if you could look into this. Thanks

**Comment by FaserF** [comment]
perfect, thanks for the Feedback :)
