### ISSUE TITLE
[Bug]: Version 2.6.0 won’t start anymore

### ISSUE THREAD

**Issue by Rothammel** [FaserF/hassio-addons#129]
### The problem

since 2.6.0 addon won't start, please see supervisor log:

`23-02-27 22:48:48 ERROR (MainThread) [supervisor.addons.addon] Add-on 605cee21_apache2 has invalid options: not a valid value. Got {'document_root': '/share/htdocs', 'php_ini': 'default', 'default_conf': 'default', 'default_ssl_conf': 'default', 'website_name': 'Wallbox', 'ssl': False, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem', 'init_commands': []}`

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.5

### What version of the addon has the issue?

2.6.0

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

**Comment by DZ8888** [comment]
same issue here!

**Comment by FaserF** [comment]
I think my latest change didn’t got into your local install with Version 2.6.0

could you please try reinstalling the Addon or add anything like
echo „Test“

into the init_commands field.

**Comment by DZ8888** [comment]
Thanks a lot for your prompt reply! Re-install cannot fix the issue but adding echo”test” to unit_command works well. Apache2 can start now. Thanks again!從我的iPhone傳送Fabian Seitz ***@***.***> 於 2023年2月28日 下午2:01 寫道：﻿
I think my latest change didn’t got into your local install with Version 2.6.0
could you please try reinstalling the Addon or add anything like
echo „Test“
into the init_commands field.

**Comment by Rothammel** [comment]
> echo „Test“

Thank you, yes, this workaround works for me too

**Comment by Rothammel** [comment]
![image](https://user-images.githubusercontent.com/42540450/222429876-b3b332a8-7231-4562-a112-40afc229542b.png)

the fix unfortunately does not help

**Comment by TJuTZu** [comment]
The problem still exist with version 2.6.1.
Configuration can't be saved and server can't be started without init command 
Adding just **test** to is enough
