### ISSUE TITLE
PDO

### ISSUE THREAD

**Issue by jcerullo** [FaserF/hassio-addons#14]
It looks like this apache2 add-on does not install php with PDO capability.  MySQLi seems to be the only allowed MySQL access method.  I'd like to request that PDO capability be allowed with this add-on.  In my case it would save a ton of work.  Thanks in advance.  John

**Comment by FaserF** [comment]
Please give it a try now. It should now be working with Version 1.5.0

**Comment by jcerullo** [comment]
Great!  I’ll let you know if it works for me.  I have a working application that I’m trying to make available in HA without having to make major code modifications.


Sent from Yahoo Mail for iPad


On Monday, November 30, 2020, 5:06 AM, Fabian Seitz <notifications@github.com> wrote:




Please give it a try now. It should now be working with Version 1.5.0

**Comment by jcerullo** [comment]
My re-instalI failed. 
I think that php7-pdo_mysql, which you previously mentioned did not exist, somehow got into your dockerfile.
I do not think that adding php7-pdo is sufficient for PDO support.  Need a driver also.
John
    On Monday, November 30, 2020, 05:06:44 AM EST, Fabian Seitz <notifications@github.com> wrote:  
 
 


Please give it a try now. It should now be working with Version 1.5.0

**Comment by RogerSelwyn** [comment]
My upgrade to 1.5.0 fails with:
```
20-11-30 22:51:20 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 605cee21/amd64-addon-apache2:1.5.0: The command '/bin/ash -o pipefail -c apk --no-cache add php7 php7-fpm php7-mysqli php7-opcache php7-gd php7-zlib php7-curl php7-phar php7-json php7-mbstring php7-mcrypt php7-zip php7-pdo php7-pdo-mysql' returned a non-zero code: 1
20-11-30 22:51:20 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_FROM
Step 2/19 : FROM $BUILD_FROM
 ---> c2cd2356d707
Step 3/19 : ENV LANG C.UTF-8
 ---> Using cache
 ---> fc169f1c5cd5
Step 4/19 : RUN mkdir /run/apache2
 ---> Using cache
 ---> 7274c18b0142
Step 5/19 : RUN apk update && apk upgrade
 ---> Using cache
 ---> 70767b202f7c
Step 6/19 : RUN apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl
 ---> Using cache
 ---> 690750e4f880
Step 7/19 : RUN apk --no-cache add php7 php7-fpm php7-mysqli php7-opcache php7-gd php7-zlib php7-curl php7-phar php7-json php7-mbstring php7-mcrypt php7-zip php7-pdo php7-pdo-mysql
 ---> Running in dcffd8ffec15
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: 
unsatisfiable constraints:


  php7-pdo-mysql (missing):
    required by: world[php7-pdo-mysql]
Removing intermediate container dcffd8ffec15
```

**Comment by jcerullo** [comment]
There is a typo in dockfile,  - instead of _  

Shouldn’t take long to fix.

Sent from Yahoo Mail for iPad


On Monday, November 30, 2020, 5:54 PM, RogerSelwyn <notifications@github.com> wrote:




My upgrade to 1.5.0 fails with:
20-11-30 22:51:20 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 605cee21/amd64-addon-apache2:1.5.0: The command '/bin/ash -o pipefail -c apk --no-cache add php7 php7-fpm php7-mysqli php7-opcache php7-gd php7-zlib php7-curl php7-phar php7-json php7-mbstring php7-mcrypt php7-zip php7-pdo php7-pdo-mysql' returned a non-zero code: 1
20-11-30 22:51:20 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_FROM
Step 2/19 : FROM $BUILD_FROM
 ---> c2cd2356d707
Step 3/19 : ENV LANG C.UTF-8
 ---> Using cache
 ---> fc169f1c5cd5
Step 4/19 : RUN mkdir /run/apache2
 ---> Using cache
 ---> 7274c18b0142
Step 5/19 : RUN apk update && apk upgrade
 ---> Using cache
 ---> 70767b202f7c
Step 6/19 : RUN apk --no-cache add apache2 php7-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl
 ---> Using cache
 ---> 690750e4f880
Step 7/19 : RUN apk --no-cache add php7 php7-fpm php7-mysqli php7-opcache php7-gd php7-zlib php7-curl php7-phar php7-json php7-mbstring php7-mcrypt php7-zip php7-pdo php7-pdo-mysql
 ---> Running in dcffd8ffec15
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: 
unsatisfiable constraints:


  php7-pdo-mysql (missing):
    required by: world[php7-pdo-mysql]
Removing intermediate container dcffd8ffec15

**Comment by FaserF** [comment]
Yes, you were right. Fixed it now. I have now tested the update and it works. Hopefully for you everything works now too.
