### ISSUE TITLE
[Bug]: Wiki.js Git Storage issue

### ISSUE THREAD

**Issue by dimmuboy** [FaserF/hassio-addons#141]
### The problem

In your the latest updated 2.5.296 is corrupted Git storage. Could you please upgrade to 2.5.298?

### What version of Home Assistant Core has the issue?

core-2023.03.2

### What version of the addon has the issue?

1.4.2

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Wiki.JS

### Log information

```txt
2023-03-29T19:58:24.417Z [MASTER] warn: Invalid or Inactive Storage Target
```

### Additional information

https://github.com/requarks/wiki/discussions/6272

**Comment by FaserF** [comment]
Thanks, Version 1.4.3 is now released

**Comment by dimmuboy** [comment]
I don't understand but issue is still there probably. Version is updated correctly to Wiki.js 2.5.298

```2023-03-30T21:41:23.572Z [MASTER] info: (STORAGE/GIT) Initializing...
2023-03-30T21:41:23.574Z [MASTER] info: (STORAGE/GIT) Checking repository state...
2023-03-30T21:41:31.849Z [MASTER] warn: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

![image](https://user-images.githubusercontent.com/12607479/228971974-e31c0e53-9a85-4890-a009-38943dcaeef2.png)

**Comment by FaserF** [comment]
On what page exactly does this issue come, as it looks like I have never seen that "Git" Part on Wikijs
Most likely this is a issue within wikijs itself

**Comment by dimmuboy** [comment]
This is in settings under storage category. I would like to backup my wiki data to git.
