### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jcerullo** [FaserF/hassio-addons#15]

**Comment by jcerullo** [comment]
In Dockerfile line 10 php7-mysqli appears twice.  Should the first instance meant to be php7-mysql ?

**Comment by FaserF** [comment]
Thanks for the feedback. The package php7-mysql does not exist. But indeed, it is twice. I will remove one of them.

**Comment by jcerullo** [comment]
Fabian -
I found out the hard way that php7-MySQL does not exist. 🙂
I would like to add php7-pdo and php7-pdo.so for PDO database access.  How do I know which php packages are available?
Thanks, John


Sent from Yahoo Mail for iPad


On Monday, November 30, 2020, 4:53 AM, Fabian Seitz <notifications@github.com> wrote:




Thanks for the feedback. The package php7-mysql does not exist. But indeed, it is twice. I will remove one of them.
