### ISSUE TITLE
Error installing the netboot.xyz add-on

### ISSUE THREAD

**Issue by ymilord** [FaserF/hassio-addons#151]
During the install I get this error.

`The command '/bin/ash -o pipefail -c echo "**** install build packages ****" && mkdir /app && apk add --no-cache --virtual=build-dependencies nodejs-npm && echo "**** install runtime packages ****" && apk add --no-cache curl dnsmasq jq nginx nodejs tftp-hpa && echo "**** install WebApp ****" && if [ -z ${WEBAPP_VERSION+x} ]; then WEBAPP_VERSION=$(curl -sX GET "https://api.github.com/repos/netbootxyz/webapp/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]'); fi && curl -o /tmp/webapp.tar.gz -L "https://github.com/netbootxyz/webapp/archive/${WEBAPP_VERSION}.tar.gz" && tar xf /tmp/webapp.tar.gz -C /app/ --strip-components=1 && npm config set unsafe-perm true && npm install --prefix /app && echo "**** cleanup ****" && apk del --purge build-dependencies && rm -rf /tmp/*' returned a non-zero code: 2`

HA ver. 2023.4.2

**Comment by FaserF** [comment]
fixed with the latest release
