### ISSUE TITLE
Cron run of php file

### ISSUE THREAD

**Issue by dmcdenissen** [FaserF/hassio-addons#16]
Hey Fabian,
Didn't know where to put this, so put it here. I was wondering if you could help me?
I'm looking to run a php (file) by cron in your apache addon. I want to run a sync.php file every minute.
Could you tell me how I can do that ?

Love the addon, keep up the good work.

Kind Regards,

Dave

**Comment by FaserF** [comment]
Hi Dave,
am I understanding it right, that you would like to have a cron job which executes your sync.php web file?
So it would also be enough to visit the website every minute? 
I dont think implementing cron into this alpine docker image makes much sense, as it would increase the addon size. 
Also it doesnt sound easy to add the cron functionality to alpine (I gave it a quick search on the web).

Have you tried using a homeassistant automation which would execute a [shell command](https://www.home-assistant.io/integrations/shell_command/) every minute?
As a shell command you could try to use something like curl https://yourwebsite/sync.php
And a trigger for example every minute.

**Comment by dmcdenissen** [comment]
Hey Fabian,
Lol, haven't looked at it that way, It could possible be a workaround for me indeed. 
normally I would have used php in cli mode because of bigger processes and the execution time, but I think I can make it work.

Thanks !
