### ISSUE TITLE
Missing iconv and DOMDocument

### ISSUE THREAD

**Issue by baloo-gh** [FaserF/hassio-addons#17]
Hi,

Super new to this, so apologies if I sound like an idiot. First, thanks for making this add-on, I am planning to use it to run TinyRSS on this. 

Background:
1. Hassio running smoothly on PI4.
2. MariaDB add-on installed, and created a SQL database there, listening/serving on port 3306. Log files all green, working well.
3. Copied TinyRSS into the \htdocs\ folder.
4. Restarted Apache.
5. TinyRSS installation routine shows up as planned (Yay, major milestone!!!)
6. Added the credentials of the DB I created in MariaDB.
7. Hit "Test Configuration"

**Getting 2 error messages now:
1. PHP support for iconv is required to handle multiple charsets
2. PHP support for DOMDocument is required, but was not found.**

![Screenshot 2020-12-15 131337](https://user-images.githubusercontent.com/45927782/102213670-5f23bb00-3ed7-11eb-9de6-c07084df60d8.png)

Does that ring a bell with you? I already pulled the php.ini file into the shared folder, so I can make changes to it. However not sure what changes I need to make so that iconv and DOMDocument are enabled?

THANKS SO MUCH in advance!

Thomas

**Comment by FaserF** [comment]
Hi Thomas,

this definitly doesnt sound like an idiot :)
This addon was kept simple, so only some neccessary php7 extensions were added.
I have now added the two missing php7 extensions your software has needed to this addon.
Please give Version 1.6.0 a try and tell me if it is now working.

**Comment by baloo-gh** [comment]
Oh my goodness, you are fast! Thanks already now a ton!

Now I just have to find out how to force my Hassio to use 1.6.0 vs the 1.5.1 which is still listed in the repository. Let me try to figure that out.

**Comment by baloo-gh** [comment]
Ah. Reloading the repository does the trick. Ok updating now, will let you know later how it goes. Need to do some home office in-between :-)

**Comment by baloo-gh** [comment]
Could not resist trying that out immediately :-)

- Good news: Error messages are gone (Thank you!). 

- However a new (seemingly less critical) error has occured: **PHP support for Internationalization Functions is required to handle Internationalized Domain Names** Any chance that this could be fixed in a 1.6.1 version possibly?

- The other two new error messages sound more like my connection to MariaDB not yet working as intended, so those likely are not caused by the Apache server you wrote.

![Unbenannt](https://user-images.githubusercontent.com/45927782/102218037-b3319e00-3edd-11eb-9f09-7033438078f7.PNG)

**Comment by jcerullo** [comment]
Fabian -
While your at it, you might want to consider adding php session variable support.  I think that session variables are extremely important in php programming.  
Just add php7-session to your dockerfile and you've got it.
John
    On Tuesday, December 15, 2020, 07:32:15 AM EST, Fabian Seitz <notifications@github.com> wrote:  
 
 


Hi Thomas,

this definitly doesnt sound like an idiot :)
This addon was kept simple, so only some neccessary php7 extensions were added.
I have now added the two missing php7 extensions your software has needed to this addon.
Please give Version 1.6.0 a try and tell me if it is now working.

**Comment by baloo-gh** [comment]
Success!!!

Managed to create the TinyRSS database and link it via the Apache Server (just had some settings wrong in both MariaDB and Apache). Now I still do not have access to the frontend of TinyRSS, but that is just a question of a couple of nights googling and figuring it out. Likely some Firewall thing with my Router.

SUPER HELP from all of you, thank you!

**Comment by baloo-gh** [comment]
Ok @FaserF,

Once again huge thanks for this add-on. I have never touched the world of Linux or Dockers so far ever, I just know how to use YAML in Home Assistant, so this was quite a ride. Here is the final outcome, and a small plea to you:

1) Pictures say more than words: Attached is the screenshot of TinyRSS working, running on your add-on. When I have time in the lockdown days to come, I will in the HA community forum post this success story, as I think a couple of peope tried to get TinyRSS on their machine and stop paying Feedly and others (I am making extensive use of RSS filtering which pretty much all vendors charge for). Open Source rocks :-)
![Screenshot 2020-12-16 104620](https://user-images.githubusercontent.com/45927782/102332435-5ccf6880-3f8c-11eb-83b0-7ae198b88ed9.png)

2) I yesterday had to create a fork as TinyRSS needed one or the other extension to be installed. So right now I am running on my forked version, though if you would agree adding the following into your docker container, everyone interested in getting Tiny RSS to run on HA could use your master. Changes are very simple, just add this to line #10 in your docker file:

php7-intl php7-soap php7-session php7-fileinfo

Now off to start configuring Tiny RSS I want it to work and save 40 Euros a year from now on. Do you have a coffee pot paypal account?

Cheers
Thomas

**Comment by FaserF** [comment]
it is now done with the new Version 1.7.0 
When I find some time it maybe would make sense to create a own addon for TinyRSS 👍🏼  Should be done quite fast

I am already happy that my addon has some users who are happy with it and I am happy for recieving a thanks.
If you still want to send something via Paypal for a coffe (or better: beer :) ) here you go: seitzf1@yahoo.de

Please give it a try with the new version
@jcerullo I have also added php7-session support in the latest version

**Comment by baloo-gh** [comment]
@FaserF, perfect! I just migrated successfully to 1.7.0. Will close my fork now (in case I find any bugs I might fork it again and then offer you a pull request). And the beer has already arrived :-)

Thanks, Merry Christmas, stay healthy!

**Comment by jcerullo** [comment]
Much thanks!  I have already successfully incorporated a pre-existing web server app into HassOS with your help.  These latest additions make your addon even more powerful.
John
    On Wednesday, December 16, 2020, 05:50:11 AM EST, Fabian Seitz <notifications@github.com> wrote:  
 
 


it is now done with the new Version 1.7.0
When I find some time it maybe would make sense to create a own addon for TinyRSS 👍🏼 Should be done quite fast

I am already happy that my addon has some users who are happy with it and I am happy for recieving a thanks.
If you still want to send something via Paypal for a coffe (or better: beer :) ) here you go: seitzf1@yahoo.de

Please give it a try with the new version
@jcerullo I have also added php7-session support in the latest version
