### ISSUE TITLE
[Question]: How to enable Headers module on apache2

### ISSUE THREAD

**Issue by viny182** [FaserF/hassio-addons#171]
### The request

Hello!

First of all, congrats on the amazing work on this addon. Specially the dedication to divide within 3 flavors, tailoring each use case.

I managed to get the minimal and standard versions running (not simultaneously, obviously), but I have not managed to enable the Request Apache2 module.

I've tried to add the command "**a2enmod headers**" to the "**init_commands**" field from the addon configuration, but the logs says that a2enmod is not found.

I've tried a generic command "echo 'test'" on the same field, and it worked perfectly, so I'm sure that the field is working correctly, is just a matter of not having a2enmod installed, or it's not on sys env patch at least.

Is there any way to enable the Header Module?

I need it to set the Header set Access-Control-Allow-Origin "*" on my .htaccess file, to enable javascript and avoid CORS validation issues...

### For which Add-On

Apache2

**Comment by viny182** [comment]
well... the phpinfo(); testpage says it has the mod_headers enabled, so i'm probably doing something stupid in my code...

![image](https://github.com/FaserF/hassio-addons/assets/65199912/0f761946-ff7d-4e67-92d6-8b78b1717a73)

**Comment by viny182** [comment]
nevermind, fixed the issue for myself...

I had to add the full address and port from the addon to the main configuration.yaml file from HA to the "cors_allowed_origins:". Also remember to add the "api". section..

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - X.X.X.X
    - X.X.X.X
  cors_allowed_origins:
    - 'null'
    - http://ADDON_SERVERIP:ADDON_PORT
    - http://ADDON_SERVERIP:ADDON_PORT/
    - 
api:

**Comment by FaserF** [comment]
Thanks for the feedback and i am glad that you got it working.
