### ISSUE TITLE
Seeking guidance on accessing addon externally without port forwarding

### ISSUE THREAD

**Issue by prbtt** [FaserF/hassio-addons#178]
### The problem

Hi there,

First of all, I want to express my appreciation for this excellent addon. It's been working flawlessly for me so far, and I'm grateful for the effort put into its development.

Currently, I have a public domain set up on my Home Assistant instance using Cloudflare. While everything works perfectly within my local network, I'm seeking guidance on how to enable access to this addon from outside my network without the need for port forwarding.

Once again, thank you for creating this fantastic addon and for any assistance you can provide.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.1

### What version of the addon has the issue?

2.7.0

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

**Comment by FaserF** [comment]
Thank you for your appreciation. 
You could use Cloudflare Argo Tunnel, then you dont need to open up a port: https://www.cloudflare.com/de-de/products/tunnel/ 

Another way would be a Proxy (f.e. Nginx Proxy Manager): https://github.com/hassio-addons/addon-nginx-proxy-manager
There you have to open Port 443, which would point to Nginx. Within nginx you can define what domains should point to which port, but you dont have to open that port at your router.
