### ISSUE TITLE
error during startup

### ISSUE THREAD

**Issue by tebeso** [FaserF/hassio-addons#18]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
SSL is deactivated
Here is your web file architecture.
ls: /var/www/localhost/htdocs/: No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

here is my config:

document_root: /share/fap
php_ini: default
default_conf: default
default_ssl_conf: default
website_name: FAP
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem

if i try to use my own 000-default.conf, i get this:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
SSL is deactivated
cp: can't create '/etc/apache2/sites-enabled/000-default.conf': No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

so for me, it looks like some permission problem.

I am running:
Home Assistant OS 5.9
Supervisor Version 2020.12.7
Home Assistant 2020.12.1

**Comment by FaserF** [comment]
Oh interesting, didnt know that I can close an issue from a commit. 

Please give it a try with the new Version 1.7.1 , it should fix both of your issues. 
If the issue persists, feel free to reopen it
