### ISSUE TITLE
Another access problem

### ISSUE THREAD

**Issue by tebeso** [FaserF/hassio-addons#19]
Hi,

thanks for fixing the bug from yesterday. That worked so far as this error didnt show up again, but now this:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
SSL is deactivated and/or you are using a custom config.
cp: can't create '/etc/apache2/sites-enabled/000-default.conf': No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

with this config:

document_root: /share/htdocs
php_ini: default
default_conf: /share/apache2/000-default.conf
default_ssl_conf: default
website_name: FAP
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem

i would assume the same will happen for the ssl conf and the php ini

**Comment by FaserF** [comment]
Please give it a new try now. 
I have fixed the issue with Version 1.7.2
