### ISSUE TITLE
[Feature Request]: Access to CLI/SSH

### ISSUE THREAD

**Issue by mikemike** [FaserF/hassio-addons#209]
### The request

It would be infinitely useful if SSH was available on the docker image in order to connect to the box to run CLI commands, or have a way to do this some other way. A huge amount of PHP applications rely on Composer, the PHP package manager, to run, which requires `composer install` to be run on deployment.

The only workaround I have to for this right now is to commit my `vendor` folder to the repository and pull that into the image using SSH. That is, of course, a really really bad idea, but after a few hours of playing about I really can't see any other way.

It also greatly limits the ability to use a database. Most applications use migrations to manage the database schema, but migrations run via the CLI, so without CLI access it's not possible to implement.

### For which Add-On

Apache2

### Is your feature request related to a problem?

```txt
Yes, I'm unable to properly deploy any application beyond very simple files to the file system. `git` is available, which makes a `git pull` workflow possible (and easy), but anything beyond that (`composer install`, `php artisan migrate` in Laravel or other frameworks, etc) is impossible currently.
```

**Comment by FaserF** [comment]
It is by design of docker that the CLI should not be accessible „easily“.
With Portainer for example you can access the CLI.

you can also use the option „init_commands“ from my Addon to send custom commands to the Addon at the start:
https://github.com/FaserF/hassio-addons/tree/master/apache2#option-init_commands
