### ISSUE TITLE
Can't create custom configuration

### ISSUE THREAD

**Issue by icservis** [FaserF/hassio-addons#21]
After changing config to custom configuration, looks like some access provillegs are insufficient:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Your custom php.ini at /share/apache2/php.ini will be used.
SSL is deactivated and/or you are using a custom config.
cp: can't create '/etc/apache2/sites-enabled/000-default.conf': No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Configuration:
document_root: /share/apache2/www/icservis/web
php_ini: /share/apache2/php.ini
default_conf: /share/apache2/conf.d/default.conf
default_ssl_conf: /share/apache2/conf.d/default-ssl.conf
website_name: home.ic-servis.com
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem

Permitions on conf.d files: 755 root root

The same problem with occures when get-config option is used.

HassIO core 2021.1.4
Apache2 addon:  latest

**Comment by icservis** [comment]
https://pasteboard.co/JKoQWUP.png

**Comment by FaserF** [comment]
I have updated the addon to Version 1.7.2 - it should now be working as expected. Please give it a try.

**Comment by icservis** [comment]
Thank you very much for lightning-fast fix, but unfortunatelly I dont see version 1.7.2, still 1.7.1. But discovering PR, it looks like workable fix.

**Comment by icservis** [comment]
Working like a magic, thx a lot !
