### ISSUE TITLE
php7 locales

### ISSUE THREAD

**Issue by icservis** [FaserF/hassio-addons#23]
It looks like there is no other locales for php usage. Using setlocale (LC_ALL, "cs_CZ.UTF-8") has no effect, decimal point is empty string, and so on. Any ideas how to fix that?

**Comment by icservis** [comment]
Solution is described here:
https://grrr.tech/posts/2020/add-locales-to-alpine-linux-docker-image/

**Comment by FaserF** [comment]
Sorry for the late reply. I have implemented it in V2.0.1 - please give it a try
