### ISSUE TITLE
[Bug]: Netboot zyz not starting

### ISSUE THREAD

**Issue by magusagnus** [FaserF/hassio-addons#232]
### The problem

Hi Fabian, 

I was trying to use one of your addons: Netboot-XYZ when I got the following error:

`s6-supervise nginx: warning: unable to spawn ./run - waiting 10 seconds`
`s6-supervise tftp (child): fatal: unable to exec run: Permission denied`
`s6-supervise tftp: warning: unable to spawn ./run - waiting 10 seconds`
`s6-supervise nginx (child): fatal: unable to exec run: Permission denied`
`s6-supervise webapp (child): fatal: unable to exec run: Permission denied`
`s6-supervise webapp: warning: unable to spawn ./run - waiting 10 seconds`
`s6-supervise dnsmasq: warning: unable to spawn ./run - waiting 10 seconds`

Would you know what is causing it?

Thanks in Advance

Rodger

### What version of Home Assistant Core has the issue?

2023.11.2 

### What version of the addon has the issue?

1.5.7

### What type of installation are you running?

Home Assistant Supervised

### Add-On causing the issue

Netboot-XYZ

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/10-prerequisite.sh
Creating user abc and setting permissions...
Generating nginx config...
Nginx port was not set! Setting 85 as default!
Linking folder /media/netboot/image to /assets and /media/netboot/config to /config.
cont-init: info: /etc/cont-init.d/10-prerequisite.sh exited 0
cont-init: info: running /etc/cont-init.d/20-nginx-config
cont-init: info: /etc/cont-init.d/20-nginx-config exited 0
cont-init: info: running /etc/cont-init.d/36-download-menus
cont-init: info: /etc/cont-init.d/36-download-menus exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun dnsmasq (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun tftp (no readiness notification)
services-up: info: copying legacy longrun webapp (no readiness notification)
s6-supervise dnsmasq (child): fatal: unable to exec run: Permission denied
s6-supervise dnsmasq: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise nginx (child): fatal: unable to exec run: Permission denied
s6-supervise nginx: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise webapp (child): fatal: unable to exec run: Permission denied
s6-supervise webapp: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise tftp: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise tftp (child): fatal: unable to exec run: Permission denied
```

**Comment by red-avtovo** [comment]
Can confirm the same on my instance

**Comment by blitzu** [comment]
Same problem here

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/10-prerequisite.sh
Creating user abc and setting permissions...
Generating nginx config...
Nginx port was not set! Setting 85 as default!
Linking folder /media/netboot/image to /assets and /media/netboot/config to /config.
cont-init: info: /etc/cont-init.d/10-prerequisite.sh exited 0
cont-init: info: running /etc/cont-init.d/20-nginx-config
cont-init: info: /etc/cont-init.d/20-nginx-config exited 0
cont-init: info: running /etc/cont-init.d/36-download-menus
cont-init: info: /etc/cont-init.d/36-download-menus exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun dnsmasq (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun tftp (no readiness notification)
services-up: info: copying legacy longrun webapp (no readiness notification)
s6-supervise dnsmasq: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise dnsmasq (child): fatal: unable to exec run: Permission denied
s6-supervise tftp (child): fatal: unable to exec run: Permission denied
s6-supervise webapp: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise webapp (child): fatal: unable to exec run: Permission denied
s6-supervise tftp: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise nginx (child): fatal: unable to exec run: Permission denied
s6-supervise nginx: warning: unable to spawn ./run - waiting 10 seconds

**Comment by NicolasGuilloux** [comment]
The `run` files from the `/etc/services.d/*` folders appear to miss the execution permission.
Moreover, it seems that some dependencies are not installed in the container. For now, I just notice that dnsmasq is missing

```
apk add dnsmasq
```

**Comment by blitzu** [comment]
it is solved

**Comment by FaserF** [comment]
Yes, should now be fixed with the release 1.6.0 thanks to @NicolasGuilloux

**Comment by magusagnus** [comment]
Hey Fabian, i've tested the 1.6.0 version and those previous errors are gone. Now i get the following error:

> services-up: info: copying legacy longrun dnsmasq (no readiness notification)
> services-up: info: copying legacy longrun nginx (no readiness notification)
> services-up: info: copying legacy longrun tftp (no readiness notification)
> services-up: info: copying legacy longrun webapp (no readiness notification)
> 
> dnsmasq: failed to bind DHCP server socket: Address in use
> listening on *:3000
> s6-rc: info: service legacy-services successfully started
> 
> dnsmasq: failed to bind DHCP server socket: Address in use
> 
> dnsmasq: failed to bind DHCP server socket: Address in use

Do you know what is causing it?

Thanks in Advance,

Rodger

**Comment by NicolasGuilloux** [comment]
The 3000 port is bound to the same port on the host. 
It apparently failed because the port is already used, meaning another program is currently using it.

Can you check if another addon uses the port 3000 and do you mind disabling it to retry NetBoot.xyz?

**Comment by red-avtovo** [comment]
Maybe instead of creating a new ticket I may ask my questions here?

I reviewed the deployment of the addon and I have some questions regarding its implementation
* Why doesn it need dnsmasq?
The original netboot [docker image](https://github.com/netbootxyz/webapp/blob/master/Dockerfile) doesn't have anything like that
* Why does it need a host network?
If you disable that it will still work and should resolve the ingress access. On top of that 3000 port could be mapped to anything after that

**Comment by red-avtovo** [comment]
I believe this addon is trying to achieve more that it should and is creating a dhcp server (correct me if I'm wrong)

**Comment by magusagnus** [comment]
> you check if another addon uses the port 3000 and do you mind disabling it to retr

Tried to find which app is using that port and some node app is using it. if i kill node from system many addons for home assistant stops working.

Tried to change the port from addon netboot configuration but it seems the addon ignores that configuration.
