### ISSUE TITLE
tado-aa not seen

### ISSUE THREAD

**Issue by BadPeeWee** [FaserF/hassio-addons#237]
### The problem

Hi.
after adding your repository to home assistant i not sse the tado-aa addon.
so i cant install. :-(

![Screenshot 2023-11-21 154012](https://github.com/FaserF/hassio-addons/assets/125493923/f288621b-95be-41dc-9bc5-2653d67ca7fd)

### What version of Home Assistant Core has the issue?

2023.11.3

### What version of the addon has the issue?

tado-aa

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Other

**Comment by FaserF** [comment]
Hi, thank you for the info. I have now fixed it with the latest release.

**Comment by BadPeeWee** [comment]
Hi
Sorry sehs noch immer nicht.
Hab dein repository gelöscht und nochmal added.
Ohne Erfolg.Was mache ich falsch?

**Comment by FaserF** [comment]
Du hast hierbei nichts falsch gemacht, es war ein Fehler in der Config. Hoffentlich sollte es nun zeitnah auftauchen.

**Comment by BadPeeWee** [comment]
Läuft jetzt.
Danke
