### ISSUE TITLE
[Bug]: Tado-AA-Plugin switches to Away-Mode

### ISSUE THREAD

**Issue by snipah** [FaserF/hassio-addons#243]
### The problem

The Tado-Plugin switches to Away-Mode inconsistently. Whenever I deactivate to plugin, the "Home/Away"-Mode can be set manually as I do not use the geofencing-function within the Tado-App. What could be the reason?

### What version of Home Assistant Core has the issue?

2023.12.1

### What version of the addon has the issue?

all

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

**Comment by FaserF** [comment]
I am sorry, but I don't think that this is a issue of this addon. Most likely it's a dependency issue which I unfortunately cannot answer you.
You can try opening a bug here at the dependency:
https://github.com/adrianslabu/tado_aa
