### ISSUE TITLE
[Bug]: switch_lan_play_server

### ISSUE THREAD

**Issue by APeeky** [FaserF/hassio-addons#244]
### The problem

When I try to install I get the error message:

The command '/bin/ash -o pipefail -c git clone https://github.com/spacemeowx2/switch-lan-play.git && cd switch-lan-play/server && npm install && npm run build' returned a non-zero code: 2

### What version of Home Assistant Core has the issue?

2023.12.1

### What version of the addon has the issue?

latest

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Switch_LAN_Play_Server

### Additional information

I found that in the config.yaml "url: https://github.com/FaserF/hassio-addons/tree/master/switch_lan_server", it shouldn't have to be "url: https://github.com/FaserF/hassio-addons/tree/master/switch_lan_play_server" ?

**Comment by FaserF** [comment]
It looks like this is an issue with the SLP project itself and needs to be fixed by them. 

For further investigating and trying a workaround: 
`"node_modules/@types/express-serve-static-core/index.d.ts(1262,1): error TS1160: Unterminated template literal."`

```
Temporary Workaround:
As a temporary workaround, you can try excluding the problematic file from the TypeScript compilation by adding an exclusion to your tsconfig.json file:

json
Copy code
"exclude": [
  "node_modules/@types/express-serve-static-core/index.d.ts"
]
This is not an ideal solution, but it can help you proceed with the build while you investigate the root cause.
```
