### ISSUE TITLE
[Bug]: freenom Addon pip install Bug

### ISSUE THREAD

**Issue by koko004** [FaserF/hassio-addons#256]
### The problem

Hi, I try to install this addon on my HASSIO server based on X86 (Intel Nuc) and I get this error when I try to install. The system is full updated, thanks and regards.

![image](https://github.com/FaserF/hassio-addons/assets/10567364/f88d21d6-9496-421f-903b-c854677fdc51)

![image](https://github.com/FaserF/hassio-addons/assets/10567364/20252e2c-2a44-4452-9f73-db2b48cb0247)

![image](https://github.com/FaserF/hassio-addons/assets/10567364/e68bec82-e0b3-4562-8bfe-c3b4792e0532)

### What version of Home Assistant Core has the issue?

2024.1.5

### What version of the addon has the issue?

1.4.9

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Freenom-DNS-Updater

**Comment by FaserF** [comment]
fixed with release 1.5.0
