### ISSUE TITLE
[Feature Request]: Enable `mod_write` for apache2

### ISSUE THREAD

**Issue by TheFes** [FaserF/hassio-addons#271]
### The request

I've setup a Wordpress website on the apache2 add-on but to be able to use the page names in the url, `mod_write` needs to be enables (see https://wordpress.stackexchange.com/questions/167144/wordpress-permalinks-not-working-in-apache2-ubuntu-14-04)

So I want to use `https://webiste.com/page_name/` instead of `https://website.com/?p=24`

Is it possible to enable this?

### For which Add-On

Apache2

**Comment by FaserF** [comment]
This is already supported, see here: https://github.com/FaserF/hassio-addons/tree/master/apache2#authentification-for-your-website

And with a custom Apache2 config file: 
https://github.com/FaserF/hassio-addons/tree/master/apache2#option-default_conf--default_ssl_conf

Those two files need to be created by yourself :)

**Comment by TheFes** [comment]
I'm a bit confused, isn't that authentication section referring to authentication for visitors of the website?

My Wordpress website works, but if I enable the permalink setting to use page names, I get errors when I try to visit the respective page, because the rewrite from Wordpress doesn't work.

Note that I don't have a lot of knowledge about all of this, so I might be missing something here :)

**Comment by TheFes** [comment]
okay, thanks, that makes it a bit more clear :)

**Comment by TheFes** [comment]
Okay, I enabled `get_config` for the `default_conf` parameter. Which downloaded a `httpd.conf` in the `/share` folder

According to the docs I have to change `path/to/your/new/apache2.conf`, but I don't know where to find that.

**Comment by TheFes** [comment]
ah okay, thanks!

**Comment by TheFes** [comment]
Thanks for your answers so far, seems I need to dig a bit more in how to setup this file before I can get it working.
