### ISSUE TITLE
Cannot find folder with default index.htm file

### ISSUE THREAD

**Issue by AirmakZ** [FaserF/hassio-addons#273]
### The problem

Even there is a possibility it's a very stupid question.... 

I installed Apache2 Add-on on my Homeassistant using Homeassitant OS.
The add-on looks working properly since I can see the default page without problem. But... where is this folder?
By default it's configured to /share/htdocs but I cannot see this folder un my 'share' folder.
I changed it to 'media' folder (the other one visible in theory by the add-on) and the subfolder name too, but I cannot see it neither.
I'm connecting to this folders using Samba add-on and I can see the rest of the content inside.

Is it stored inside another path instead of default homeasssitant /share and /media folders?

### What version of Home Assistant Core has the issue?

2024.3.0

### What version of the addon has the issue?

2.7.10

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
You haven't put your website to /media/apache2docs
A default website will now be used
SSL is deactivated and/or you are using a custom config.
Here is your web file architecture.
total 8
-rwxr-xr-x    1 root     root          7057 Mar  9 17:42 index.html
Starting Apache2...
[Sat Mar 09 17:42:37.224465 2024] [mpm_prefork:notice] [pid 79] AH00163: Apache/2.4.58 (Unix) PHP/8.1.27 OpenSSL/3.1.4 mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
[Sat Mar 09 17:42:37.224490 2024] [core:notice] [pid 79] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

**Comment by FaserF** [comment]
The default website comes from within the addon itself and is stored nowhere accessible from your HA folders. You can put your own folder somewhere to /share or /media and configure this path in the addon settings to display your own webpage 

The folder /share/htdocs isn't created automatically and needs to be created by yourself with your own webpage content.

**Comment by AirmakZ** [comment]
Oh god.... ok ok.... Sorry.... I misunderstood.
Really appreciate your quick help!
