### ISSUE TITLE
[Bug]: Change default page

### ISSUE THREAD

**Issue by TGRDMS** [FaserF/hassio-addons#274]
### The problem

Hi, i am new with Home Assistant and i'm trying configure Apache2.
I have installed this add-on and the default page is working, but when tried to change the default page to my html or php page does't works.
The file is located in /root/share and i setup this location in document_root but doesn't work. Could you help me?

### What version of Home Assistant Core has the issue?

core-2024.3.2

### What version of the addon has the issue?

2.7.10

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
You haven't put your website to /var/www/localhost/htdocs/
A default website will now be used
No username and/or password was provided. Skipping account set up.
SSL is deactivated and/or you are using a custom config.
Here is your web file architecture.
total 8
-rwxr-xr-x    1 root     root          7057 Mar 22 13:22 index.html
Starting Apache2...
[Fri Mar 22 13:22:34.905606 2024] [mpm_prefork:notice] [pid 79] AH00163: Apache/2.4.58 (Unix) PHP/8.1.27 OpenSSL/3.1.4 mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
[Fri Mar 22 13:22:34.905669 2024] [core:notice] [pid 79] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri Mar 22 13:22:59.888863 2024] [php:error] [pid 144] [client 192.168.1.234:25443] script '/var/www/localhost/htdocs/index.php' not found or unable to stat
192.168.1.234 - - [22/Mar/2024:13:22:59 -0300] "GET /index.php HTTP/1.1" 404 273
[Fri Mar 22 13:23:06.832448 2024] [php:error] [pid 145] [client 192.168.1.234:25444] script '/var/www/localhost/htdocs/index.php' not found or unable to stat
192.168.1.234 - - [22/Mar/2024:13:23:06 -0300] "GET /index.php HTTP/1.1" 404 273
```

### Additional information

I had created the path "/var/www/localhost/htdocs" changed "document_root" to this directory but doesn't work

**Comment by FaserF** [comment]
Hi, please have a look here at the "Note" part: https://github.com/FaserF/hassio-addons/tree/master/apache2#option-document_root

Please put you webpage files somewhere at /share or /media and define it within that configuration option in the addon configuration page. Then it should be working.

**Comment by TGRDMS** [comment]
Hi FaserF! Thank you for your reply! It works!
Thanks a lot of!
