### ISSUE TITLE
[Feature Request]: Sqlite3

### ISSUE THREAD

**Issue by rektosaure** [FaserF/hassio-addons#279]
### The request

Hi,
Is it possible to produce a version using sqlite3 instead of mariadb?
Thanks

### For which Add-On

Apache2-Minimal-MariaDB

**Comment by FaserF** [comment]
Hi, this definitly is possible, but since there is no offical SQLite3 addon for Homeassistant, this makes it kind of hard to seamlessly integrating it to SQLite3. And this Addon will not deploy a full sqlite3 database with it. Are you using a custom addon for sqlite3?
