### ISSUE TITLE
Permissions with Wordpress

### ISSUE THREAD

**Issue by Marvilius** [FaserF/hassio-addons#28]
Hello!

I want to express my thanks for the plugin. Very good one!

But i have a problem with wordpress. Whenever i try to install a plugin, i get a popup for ftp credentials. I tried my local hassio user and root. Both dont work. Even setting chmod to 777 via terminal does not help. Do i need to chown the htdocs folder to a group/user? if so, which group or user do i need to set?

Thanks for your help

**Comment by FaserF** [comment]
Hi,

As this Addon runs within a docker container, the credentials you know from HA are not valid.
I will update the Addon to generate a user with the necessary permissions in the next days.

**Comment by Marvilius** [comment]
Thank you for your fast reply. And please Update the documentation, not that i need to nag again, howto ftp to the htdocs folder then.

thank you…

**Comment by FaserF** [comment]
Give it a new try with V2.0.2 - I have implemented it

And for instructions how to ftp to the htdocs folder:
Just ftp to your HA OS instance and use the folder on your /share folder.
The addon itself will do the rest.

**Comment by Marvilius** [comment]
Hey there!

Thanks for your hard work....But sadly it still asks for ftp when trying to install a plugin in the dashboard
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Apache2
 OpenSource Webserver
-----------------------------------------------------------
 Add-on version: 2.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.0
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
chpasswd: password for 'papi' changed
You have activated SSL. SSL Settings will be applied
Here is your web file architecture.
total 216
-rwxrwxrwx    1 papi     www-data       422 May  3 21:04 index.php
-rwxrwxrwx    1 papi     www-data     19915 May  3 21:04 license.txt
-rwxrwxrwx    1 papi     www-data      7442 May  3 21:04 readme.html
-rwxrwxrwx    1 papi     www-data      7386 May  3 21:04 wp-activate.php
drwxrwx--x    9 papi     www-data      4096 May  3 21:04 wp-admin
-rwxrwxrwx    1 papi     www-data       372 May  3 21:04 wp-blog-header.php
-rwxrwxrwx    1 papi     www-data      2409 May  3 21:04 wp-comments-post.php
-rwxrwxrwx    1 papi     www-data      2913 May  3 21:04 wp-config-sample.php
-rwxrwxrwx    1 papi     www-data      3206 May  3 21:07 wp-config.php
drwxrwx--x   10 papi     www-data      4096 May  4 08:25 wp-content
-rwxrwxrwx    1 papi     www-data      4091 May  3 21:04 wp-cron.php
drwxrwx--x   25 papi     www-data     12288 May  3 21:05 wp-includes
-rwxrwxrwx    1 papi     www-data      2593 May  3 21:04 wp-links-opml.php
-rwxrwxrwx    1 papi     www-data      3406 May  3 21:04 wp-load.php
-rwxrwxrwx    1 papi     www-data     46428 May  3 21:04 wp-login.php
-rwxrwxrwx    1 papi     www-data      8773 May  3 21:04 wp-mail.php
-rwxrwxrwx    1 papi     www-data     21707 May  3 21:04 wp-settings.php
-rwxrwxrwx    1 papi     www-data     32342 May  3 21:04 wp-signup.php
-rwxrwxrwx    1 papi     www-data      4899 May  3 21:04 wp-trackback.php
-rwxrwxrwx    1 papi     www-data      3341 May  3 21:04 xmlrpc.php
Starting Apache2 - This is the last message in the log. If no error occured your web server should work.`

This is all I get, no error messages or so.....

Thanks

**Comment by FaserF** [comment]
I have misunderstood your issue.
The Addon itself doesnt come with FTP Access.

You could try the following:
Install the FTP Addon: https://github.com/hassio-addons/addon-ftp

And then give it a try if it works with the credentials saved there.
Let me know if this works.

**Comment by Marvilius** [comment]
I did it that way. I created the user with same password in Cassio, ftp and apach2, and installation went fine. but when I try to install an add-on, it shows up like that

**Comment by FaserF** [comment]
Maybe have a look at #50 - there seems to be a solution
