### ISSUE TITLE
Don't find the folder /share/htdocs

### ISSUE THREAD

**Issue by wavoigt** [FaserF/hassio-addons#297]
### The problem

Home Assistant Supervised on a Raspberry 4
Now i've installed Apache 2.
All seems to work fine, I see the welcome screen on Port 80.
Now, i don't find the folder /share/htdocs
I tried it with HA File Editor, then VNC and File manager and Filezilla.
How can i find the folder?
In the HA sidebar, if i click on "Apache2", following message appears:
<pre>Apache2
Das Add-on scheint noch nicht bereit zu sein, möglicherweise startet es noch. Willst du es nochmal versuchen?</pre>
My Apache configuration:
<pre>document_root: /share/htdocs
php_ini: default
default_conf: default
default_ssl_conf: default
website_name: mywebsite
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
init_commands: []
</pre>
My Apache Protocol:
<pre>Apache2
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
You haven't put your website to /share/htdocs
A default website will now be used
SSL is deactivated and/or you are using a custom config.
Here is your web file architecture.
total 8
-rwxr-xr-x    1 root     root          7057 Jul 10 17:29 index.html
Starting Apache2...
[Wed Jul 10 17:29:03.982335 2024] [mpm_prefork:notice] [pid 79:tid 79] AH00163: Apache/2.4.61 (Unix) PHP/8.2.21 OpenSSL/3.3.1 mod_wsgi/5.0.0 Python/3.12 configured -- resuming normal operations
[Wed Jul 10 17:29:03.982465 2024] [core:notice] [pid 79:tid 79] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
192.168.178.21 - - [10/Jul/2024:17:29:26 +0200] "GET / HTTP/1.1" 200 7057
192.168.178.21 - - [10/Jul/2024:17:29:26 +0200] "GET /favicon.ico HTTP/1.1" 404 273
192.168.178.21 - - [10/Jul/2024:17:30:18 +0200] "-" 408 -
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[Wed Jul 10 17:39:52.424637 2024] [mpm_prefork:notice] [pid 79:tid 79] AH00169: caught SIGTERM, shutting down
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
You haven't put your website to /share/htdocs
A default website will now be used
SSL is deactivated and/or you are using a custom config.
Here is your web file architecture.
total 8
-rwxr-xr-x    1 root     root          7057 Jul 10 17:43 index.html
Starting Apache2...
[Wed Jul 10 17:43:04.790754 2024] [mpm_prefork:notice] [pid 79:tid 79] AH00163: Apache/2.4.61 (Unix) PHP/8.2.21 OpenSSL/3.3.1 mod_wsgi/5.0.0 Python/3.12 configured -- resuming normal operations
[Wed Jul 10 17:43:04.790869 2024] [core:notice] [pid 79:tid 79] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
172.30.32.1 - - [10/Jul/2024:17:48:14 +0200] "GET / HTTP/1.1" 200 7057
172.30.32.1 - - [10/Jul/2024:17:48:16 +0200] "GET / HTTP/1.1" 304 -
172.30.32.1 - - [10/Jul/2024:17:48:21 +0200] "GET / HTTP/1.1" 304 -
172.30.32.1 - - [10/Jul/2024:17:49:05 +0200] "-" 408 -</pre>

### What version of Home Assistant Core has the issue?

2024.7.2

### What version of the addon has the issue?

latest

### What type of installation are you running?

Home Assistant Supervised

### Add-On causing the issue

Apache2

**Comment by FaserF** [comment]
Hi, you wont find the /share folder from the HA editor. You can access it from within the Operating system or by transferring the files via FTP for example. 

See also https://www.reddit.com/r/homeassistant/comments/104qg4p/whatwhere_is_the_share_folder/

**Comment by franciscoasencio** [comment]
Good day Sir. Thank you for the developement. I have Apache2 full installed now. a) Got same message stating " The add-on seems to not be ready, it might still be starting. Do you want to try again?" and nothing I do seems to work. Got MariaDB addon installed also. Reports working, DB created. b) I have SAMBA share working , do I have access to share/htdocs this way . ( not yet as the Apache addon seems not to work ( no web ui access ).

**Comment by FaserF** [comment]
@franciscoasencio 
You can access the /share folder from a FTP Client or samba or from the terminal with OS access. The /share/htdocs folder needs to be created on your own and does not exist per default. 
If the addon is stuck on starting, please send over the log, otherwise I won't be able to support you.

**Comment by wavoigt** [comment]
Hi Fabian,
Thank you for your answer.
I now installed Apache directly under Raspbian OS and all is working fine.

**Comment by franciscoasencio** [comment]
> If the addon is stuck on starting
![image](https://github.com/user-attachments/assets/c02ead6a-4c08-45aa-8894-3b16f1f9611a)

This is the log.

![image](https://github.com/user-attachments/assets/35c66bd4-f54a-46b4-b5bb-8d11c7f4c9d4)


 I already created htdocs , even the application folder that I want to implement. I installed OpenSSL and try to fix that one. Thank you for prompt answer. Will continue to report. Greetings

**Comment by franciscoasencio** [comment]
> I installed OpenSSL

error 502 whent away . Installed both cert and key generated by OpenSSL.

On opening web ui , blank page , now log look like this
![image](https://github.com/user-attachments/assets/a835fc54-7528-4aec-bd01-cf3307c053f8)

This time my share/htdocs folder is empty ( deleted everything else )

**Comment by franciscoasencio** [comment]
![image](https://github.com/user-attachments/assets/42d2e511-524c-4832-9d71-012e05fb7bbc)

Uninstall & reinstall
Put simple index.html into htdocs.  only 

![image](https://github.com/user-attachments/assets/d3bb0c7b-8aa8-40ea-86a6-00faffd8ba6e)

Result in web ui

![image](https://github.com/user-attachments/assets/e855757e-b226-43ae-aa10-46909c780985)

Readmanual in Github carefully once again.
do not know what else to do
Thank you for support

**Comment by franciscoasencio** [comment]
![image](https://github.com/user-attachments/assets/1c9f5385-4c46-45c6-b63d-82bed755f701)

Direct access to the ip.
Works !
Thank you

My goal is to make an emomncms install work inside HAOS. Emoncms is an energy monitoring system coded in php and works in conjunction with MariaDb.
We will see if oit works.
Greetings
