### ISSUE TITLE
Apache | Feature request | Mosquitto-PHP support

### ISSUE THREAD

**Issue by niro1987** [FaserF/hassio-addons#3]
I would like to see support added for the [Mosquitto-PHP extention](https://github.com/mgdm/Mosquitto-PHP).
Mosquitto-PHP can be used to relay website input to HomeAssistant.

**Comment by FaserF** [comment]
I have just added Mosquitto-PHP support to the apache2 full addon.
Please give it a try, as I am unable to test it.

**Comment by niro1987** [comment]
You are too kind. I will most certainly give it a spin. I applaud you good sir!

**Comment by niro1987** [comment]
I can confirm it is working. Thank you!
