### ISSUE TITLE
ingress problem

### ISSUE THREAD

**Issue by PM04290** [FaserF/hassio-addons#30]
Hi,
i can use my php web site but i have a problem with ingress using and nothing to use it in readme or documentation.
when i call http page in menu, i'm using href by /page1.html or /page2.php, real link (seen in bottom of page) is 192.168.0.100:8123/page1.html; corresponding to HTTP_HOST in apache Environnement.
Over application in H.A. , like phpmyadmin or others, indicate full link like 192.168.0.100:8123/api/hassio_ingress/###ingress_key###/index.php , for exemple.
How to have a complete HTTP_HOST including ingress key ?

**Comment by FaserF** [comment]
Hi,
as written here: https://github.com/FaserF/hassio-addons/blob/master/apache2/README.md#ingress 
I am sad to say that I dont think there is a way to get this working. The only way would be that you were writing a complete new HA Addon just for your specific usage.

**Comment by PM04290** [comment]
hi,
it's not a specific usage, it's the only way to not have a 404 error caused by ingress.
