### ISSUE TITLE
[Bug]: run.sh still points to php 8.1

### ISSUE THREAD

**Issue by bertjanwezeman** [FaserF/hassio-addons#305]
### The problem

phppath=/etc/php81/php.ini this should be phppath=/etc/php82/php.ini

### What version of Home Assistant Core has the issue?

2024.8.1

### What version of the addon has the issue?

 2.8.3

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2-Minimal-MariaDB

### Log information

```txt
cp: can't stat '/etc/php81/php.ini': No such file or directory
```

**Comment by FaserF** [comment]
Thank you for pointing out! Fixed with verion 2.8.4
