### ISSUE TITLE
[Feature Request]: Planka (NEW ADDON)

### ISSUE THREAD

**Issue by User7872953326** [FaserF/hassio-addons#322]
### The request

Is it possible to add Planka Kanban boards as a new addon? It would really be so great as Planka is a tooles tool for planning and organization.

https://planka.app/
https://github.com/plankanban/planka/blob/master/docker-compose.yml
Docker-compose.yml: https://github.com/plankanban/planka/blob/master/docker-compose.yml

### For which Add-On

Other

### Is your feature request related to a problem?

It's not related to a specific problem, but it would be great to be able to use this tool as a Home Assistant addon.

**Comment by FaserF** [comment]
Thanks for the idea. Unfortunately since I don't use this tool by myself, it makes little sense to add this addon, as I can't really give support on issues then. I will keep an eye on the issue and if it's easy to support and build an addon, I will add it to the addon store here. 👍🏼

**Comment by FaserF** [comment]
Hey, unfortunatly the addon did not work yet with my progress from then, this was the reason that it was a draft and has not been mergerd. 
Didnt find a solution and therefore no progress has been made
