### ISSUE TITLE
mysql root password

### ISSUE THREAD

**Issue by farxpeace** [FaserF/hassio-addons#34]
May i know what is the mysql root username and password?

**Comment by FaserF** [comment]
Hi,
this addon doesnt come with a MariaDB (mysql DB) itself. You have to install the [MariaDB Addon](https://github.com/home-assistant/addons/tree/master/mariadb), there you can create Users and manage passwords yourself.

**Comment by farxpeace** [comment]
Alright understood. Thanks ya for the reply.
