### ISSUE TITLE
Apache | Feature Request | Self-Signed SSL

### ISSUE THREAD

**Issue by niro1987** [FaserF/hassio-addons#4]
Some services require a valid SSL certificates to be installed on the webserver. When the config `ssl = false` is set, the webserver should create a self-signed certificate.

**Comment by FaserF** [comment]
Thanks for your feature request. As I dont want to "blow up" a current addon. I have created a new addon for this specific usage: 
https://github.com/FaserF/hassio-addons/tree/master/openssl

With this new addon, you can create a self signed certificate. Afterwards you can use that certificate with my apache2 addon.

If you have any improvements, let me know it :)
