### ISSUE TITLE
Option to Change "Apache 2" on the Hassio Side Bar

### ISSUE THREAD

**Issue by makerph** [FaserF/hassio-addons#40]
**Is your feature request related to a problem? Please describe.**
Request to have an option to change the "Apache 2" on the sidebar to a something related to the application uses the apache2 addon

**Comment by FaserF** [comment]
You mean that in the HA sidebar doesn’t stand „Apache2“. Instead there should stay the name of the service / website you are running ?

if yes -> this is not possible due to HA Addon Limitations

**Comment by makerph** [comment]
yes your right change apache 2 to the service name/website I'm running. since its a limitation I'll stick with it :)
