### ISSUE TITLE
How to see the webserver outside

### ISSUE THREAD

**Issue by danisk89** [FaserF/hassio-addons#47]
Great addon!!!
I just installed the addon. How can I do to see outside the webserver?
I have some api and i want to call them

**Comment by FaserF** [comment]
The addon provides a webserver just like a manual installation.
You can access it by visiting it in a webbrowser with

if SSL enabled:
https://IP-of-your-HA-server

or if  SSL is disabled: 
http://IP-of-your-HA-server

if you have changed the default ports you can access it with:
if SSL enabled:
https://IP-of-your-HA-server:YourPort

or if  SSL is disabled: 
http://IP-of-your-HA-server:YourPort


I am also using a own created api and call it for example by:
https://192.168.188.10/api/myapi



Does that answer your question?

**Comment by danisk89** [comment]
i use alexa, and my port is 8123 so when i go to https://my_address:my_port,
it redirect me to hassio frontend

Il giorno mar 9 nov 2021 alle ore 10:10 Fabian Seitz <
***@***.***> ha scritto:

**Comment by FaserF** [comment]
8123 is the port of your Homeassistant Installation.
Every addon (not only mine) uses its own port. By default it will be 443 and 80.
![image](https://user-images.githubusercontent.com/12374134/140921015-b065d7a6-79b7-46bd-afd1-792bc3aae11a.png)


so try going to: https://my_address
if you havent changed the default ports.

**Comment by danisk89** [comment]
Awesome, thanks! I don't see them, perfect, great solution!!

Il mar 9 nov 2021, 13:04 Fabian Seitz ***@***.***> ha scritto:
