### ISSUE TITLE
Apache | Open Web UI results in 502: Bad Gateway

### ISSUE THREAD

**Issue by niro1987** [FaserF/hassio-addons#5]
The **Open Web UI** button results in an error `502: Bad Gateway` while `http://<homeassistant_ip>` does return a valid page.

**Comment by niro1987** [comment]
Sorry to be spamming you with *issues*. I'll try to help out where I can with PR's.
Love the work that you did, great addon! This is wat homeassistant was missing!

**Comment by FaserF** [comment]
Dont worry about spamming. I am happy about any contribution, new Ideas and bug reportings.
I will take a deeper look at the issue again, until now I havent fully understood how exactly ingress in homeassistant is working. 
A similar issue also happens sometimes at the tasmoadmin addon (at least for me)

**Comment by niro1987** [comment]
I've posted a questing in https://discord.me/hassioaddons

**Comment by niro1987** [comment]
https://developers.home-assistant.io/docs/add-ons/presentation/#ingress

**Comment by FaserF** [comment]
I have just tested the ingress support again, my personal website works (but it is kinda being wrong displayed, most likely due to the use of css and so on). On my test HA instance it also works with the new default apache2 page:
![image](https://user-images.githubusercontent.com/12374134/88385795-54914980-cdaf-11ea-95dc-efc89a8b2374.png)

Can you try reinstalling my addon and then use a path in the config that is empty -> So my default page will be used
And then give me a short feedback if it works for you?

**Comment by niro1987** [comment]
Let me try later. Can I use the ssl addon to get a certificate for an internal ip?

**Comment by FaserF** [comment]
I think in general it is possible to generate a self signed certificate for an IP, but it is more complicated.
I haven't tested it, but if your device has a hostname, just use the hostname for the certificate, that should work fine.

**Comment by MarcoPereira00** [comment]
Hi, im having the same issue, im new to all of this. I wanna acess to a html file that is on my Raspberry on /share/htdocs directory, had configured the addon just how you have on your example but cant open the html file.

**Comment by MarcoPereira00** [comment]
I see the error when I click on Open Web UI. I have NGINX add-on installed, something else is needed?

**Comment by PM04290** [comment]
Hi, i have the same problem, 502: Bad gateway when i click ti sidebar.
If i start addon with SSL i have an error because i don't know configuring certfile and keyfile; and if i start without SSL, addon stating well but i have 502 error.
what is the mistake ?
PS : index.html is detected at start.

**Comment by FaserF** [comment]
> I see the error when I click on Open Web UI. I have NGINX add-on installed, something else is needed?

What NGINX Addon do you mean? This addon is a Apache2 Addon. 
To fix the 502 error HTTPS (SSL) is needed, have you configured your SSL certificates for the addon?



> Hi, i have the same problem, 502: Bad gateway when i click ti sidebar.
> If i start addon with SSL i have an error because i don't know configuring certfile and keyfile; and if i start without SSL, addon stating well but i have 502 error.
> what is the mistake ?
> PS : index.html is detected at start.

How do you have configured your SSL Entries? Have you access to your fullchain.pem and privkey.pem? How have you configured your SSL files? With my OpenSSL Addon, Certbot or in another way?

**Comment by PM04290** [comment]
Problem is solved with you OpenSSL addon and SSL activation
