### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by dimmuboy** [FaserF/hassio-addons#52]
**Describe the bug**
When I try to install Freenom-dns-updater it throws me error

```The command '/bin/bash -o pipefail -c apk add --no-cache zlib openssl-dev binutils' returned a non-zero code: 13```

**Expected behavior**
It should be installed

**What Addon?**
 - Addon Name: Freenom-dns-updater
- Addon Version: 1.1.0

**Comment by FaserF** [comment]
Should now be working again.

OpenSSL-dev contains a bug in the latest Alpine version which was released on the 18th december, therefore I switched back to hassio addon base 7.2.0 to install an older version of openssl 1.1.1l-r0 (V3.14).
