### ISSUE TITLE
Not able to use correctly a site with php file and sqlite db

### ISSUE THREAD

**Issue by zaromarco** [FaserF/hassio-addons#53]
Hi , i have just installed your addon , configuration is very simple , i haven't modified nothing except ssl = false
then in share i create manually htdocs dir with this property:
![immagine](https://user-images.githubusercontent.com/13431840/147991561-50023842-4d5c-430e-bdb7-a1bd5972ed0a.png)

then i copied php file etc into htdocs, tried to get to login page , which was shown but after inserting password it throw error "something goes wrong"
the developer of php file told me it is a problem on security settings of db file....
question: root is ok for htdocs ?
these are the property of all file and dirs:
![immagine](https://user-images.githubusercontent.com/13431840/147991936-3b995740-146c-494c-9ab8-6c97566c9838.png)
let me know

**Comment by FaserF** [comment]
Hi, could you try this:
https://github.com/FaserF/hassio-addons/issues/50#issuecomment-991613113
Most likely its a permission issue of these files as you say.

The strange thing is that my addon overrides the permissions within the addon, but it looks like for some files it fails.

**Comment by zaromarco** [comment]
tried with no luck....

Il giorno mar 4 gen 2022 alle ore 09:04 Fabian Seitz <
***@***.***> ha scritto:
