### ISSUE TITLE
Wiki.js - Failed to setup HTTPS server parameters:

### ISSUE THREAD

**Issue by rvanarkel** [FaserF/hassio-addons#59]
When SSL option is enabled the addon fails to start. The log gives the following error
2022-02-25T18:56:14.901Z [MASTER] info: HTTPS Server on port: [ 3443 ]
2022-02-25T18:56:14.902Z [MASTER] error: Failed to setup HTTPS server parameters:
2022-02-25T18:56:14.902Z [MASTER] error: ENOENT: no such file or directory, open 'privkey.pem'

The SSL files are present in the SSL folder, both fullchain.pem and privkey.pem.

![image](https://user-images.githubusercontent.com/74653970/155772190-0db71696-a825-49eb-becb-cd9b526fa40c.png)

**What Addon?**
 - Addon Name: wiki.js
- Addon Version: 1.2.1

Without SSL enabled the addon runs fine by the way.

**Comment by FaserF** [comment]
I have just tested it and for me everything works fine. The error shows to me that the file "privkey.pem" is missing in the /ssl/ directory.
Could you check that?

Nevertheless have I improved that warning with V1.2.2

https://github.com/FaserF/hassio-addons/commit/3c4af4bb999b15e3758d601ef6210df402d5e7b8

**Comment by dimmuboy** [comment]
I have same issue with 1.2.2 too. I have certificate files in /ssl/ I tried to move them to /config/ssl/ but doesn't work.
It returns error
```
You have activated SSL. SSL Settings will be applied
Cannot find certificate file fullchain.pem . Turn off SSL or check for if the file really exists at /ssl/
[cmd] /run.sh exited 1
```
When I try to disable SSL it can start but ingress doesn't work, only direct acces via port.

**Comment by FaserF** [comment]
Can you both check the permissions of the fullchain.pem file ?

At /config/ssl it wont work, it definitly has to be at the /ssl/ folder.
Does the ssl certificate work with other addons? (for example the apache2 addon)

**Comment by dimmuboy** [comment]
My fullchain.pem have 644 and privkey.pem 600 but no change helps. I tried to change it to 755

**Comment by FaserF** [comment]
sorry for the late fix, it should now be working

**Comment by samplename0** [comment]
I am having the same issue. I am running Wiki.js on version 1.3.0. The SSL files are in the correct folder and it works fine with apache2 minimal addon. 

> 2022-06-14T12:28:29.203Z [MASTER] error: Failed to setup HTTPS server parameters:
> 2022-06-14T12:28:29.205Z [MASTER] error: ENOENT: no such file or directory, open 'privkey.pem'

**Comment by FaserF** [comment]
found another bug. Should now hopefully really be working with V1.3.1
