### ISSUE TITLE
Apache2 version 2.4.1 causes an error: Error loading shared library mosquito.so.so

### ISSUE THREAD

**Issue by willys52** [FaserF/hassio-addons#75]
Apache2 version 2.4.1 produces an error in the log.

PHP Warning: PHP Startup: Unable to load dynamic library 'mosquitto.so' (tried: /usr/lib/php81/modules/mosquitto.so (Error loading shared library /usr/lib/php81/modules/mosquitto.so: No such file or directory), /usr/lib/php81/modules/mosquitto.so.so (Error loading shared library /usr/lib/php81/modules/mosquitto.so.so: No such file or directory)) in Unknown on lines 0

Worked fine with version 2.2.2.
Home Assistant is up to date.
Even with a new installation of Homeassistant and Apache2 the same error

**Comment by FaserF** [comment]
Unfortunately the developer from mosquitto PHP has dropped supporting its module, so right now PHP8 is not supported:
https://github.com/mgdm/Mosquitto-PHP/issues/121

Therefore I had to drop support with V2.4.0:
https://github.com/FaserF/hassio-addons/commit/0bc1d521e8b067f2d93d55559a75e69baf593377

I will try to see if I can implement this fork:
https://github.com/mgdm/Mosquitto-PHP/pull/125

Or maybe this would be an alternative, which seems to have great support?
https://github.com/php-mqtt/client

**Comment by FaserF** [comment]
thanks for the feedback and praise, I had forgotten to remove thath php config. It is removed now and will be removed within the next addon release. If you want the changes now already, you can do a rebuild within the addon settings of apache2.

**Comment by willys52** [comment]
Thank you, works perfectly!!
