### ISSUE TITLE
Failed to install add-on - Apache2 Minimal

### ISSUE THREAD

**Issue by zephirus** [FaserF/hassio-addons#88]
I'm having this error when installing Apache2 Minimal:

Failed to install add-on
The command '/bin/ash -o pipefail -c apk --no-cache add apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 5

I'm on a Raspberry Pi 4 4Gb, HA Supervisor 2022.08.3

**Comment by FaserF** [comment]
I am unable to reproduce it. Could you check #33 ?

Can you give me details about your setup?

What DNS server are you using (Internet provider, google, cloudflare, PiHole, Adguard?)
Any VPN used?
What OS Used (if Homeassistant OS, please share the HA OS version) 
Your country

**Comment by zephirus** [comment]
I have Adguard inside HA. I shared the HA OS version already.

**Comment by zephirus** [comment]
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:123
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 00:27:59 (7 occurrences)
Last logged: 11:11:36

Failed to to call /addons/605cee21_apache2-minimal/install - The command '/bin/ash -o pipefail -c apk --no-cache add apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 5
Failed to to call /addons/605cee21_apache2/install - The command '/bin/ash -o pipefail -c apk --no-cache add apache2 php81-apache2 libxml2-dev apache2-utils apache2-mod-wsgi apache2-ssl' returned a non-zero code: 6

**Comment by FaserF** [comment]
Thanks for the informations. What DNS Server are you using inside Adguard? Cloudflare, Google?
Are you able to install any other of my addons? (For example OpenSSL)

You have shared your HOmeassistant Supervisor Version, that is different to the HA OS version.
Under System -> About you can find the information
![image](https://user-images.githubusercontent.com/12374134/186143559-fafa91fb-73e8-410e-8162-d70f263f5990.png)

**Comment by zephirus** [comment]
Home Assistant 2022.8.6
Supervisor 2022.08.3
Frontend 20220802.0 - latest

I tried disabling AdGuard but still the issue occurs.

Trying to insall OpenSSL, I get this error:

The command '/bin/ash -o pipefail -c apk update && apk upgrade' returned a non-zero code: 2

![image](https://user-images.githubusercontent.com/11021889/186146216-4f2596b9-78c3-4103-bb7e-4191c25e8ca4.png)

**Comment by FaserF** [comment]
If other addons also wont work then it is most likely a Supervised issue (as you are not running Homeassistant OS), or a DNS issue. 
Unfortunatly we have not found a solution, or I havent heard a solution from the users in issue 33 yet. 
With HA OS and default DNS providers everything works as it should.

I am using those DNS Upstream Servers in Adguard Home, maybe you can give them a try for a test:

```
https://dns.cloudflare.com/dns-query
https://dns10.quad9.net/dns-query
tls://1.1.1.1
```

**Comment by zephirus** [comment]
I will try that.

Btw, I just want to have a way to access some files that are in HA, instead of using a host I have where I build my websites. Is there a quick way? I just need to have the files there, I don't need php, dbs, etc

**Comment by FaserF** [comment]
you can use FTP for that. If you need access from outside your network , you could publish that port within your router. 
I would not recommend using port 22 then.
https://community.home-assistant.io/t/home-assistant-community-add-on-ssh-web-terminal/33820

If you need it via a website, then your solution would only be this addon here with a simple html website.

**Comment by zephirus** [comment]
Ok thanks. So, about this error, it's related with the OS I'm using, right?

**Comment by FaserF** [comment]
I am not sure, as what I have read on the issue #33 from the other users, this error never occurs with the Homeassistant OS itself using a compatible DNS provider. 
mabye something with the OS DNSmasq etc.
