### ISSUE TITLE
request feature: multiple host

### ISSUE THREAD

**Issue by giurest** [FaserF/hassio-addons#9]
hi, is there a method to implement vhosts in this addons? https://cwiki.apache.org/confluence/display/HTTPD/ExampleVhost

**Comment by FaserF** [comment]
Hi, right now the apache addon is already using virtual hosts for port 80 (http) and port 443 (https), what additional vhost would you like to see in the addon?

**Comment by giurest** [comment]
hi, vhosts per project for example 

project1 
  docroot: shared/projects/project1 
  nameserver: project1 
project2 
 docroot: shared/projects/project2
 nameserver: project2

**Comment by FaserF** [comment]
Please update the addon to version 1.4.0 
You can now use your own apache2 config files. mentioned here: https://github.com/FaserF/hassio-addons/tree/master/apache2#option-default_conf--default_ssl_conf 

This should make your feature request now possible.
