### ISSUE TITLE
[Bug]: Error installing version 2.4.6 of Apache2

### ISSUE THREAD

**Issue by Rogelage** [FaserF/hassio-addons#95]
### The problem

Error installing version 2.4.6 of Apache2

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.7

### What version of the addon has the issue?

2.4.6

### What type of installation are you running?

Home Assistant Supervised

### Add-On causing the issue

Apache2

### Log information

```txt
The command '/bin/ash -o pipefail -c mkdir /usr/lib/php81/modules/opcache' returned a non-zero code: 1
```

### Additional information

I have tried to install the version "Apache2 Minimal with MariaDB Client 2.4.6" and it has been installed correctly.
But I need to install the full version.

**Comment by FaserF** [comment]
Thanks for letting me know. Fixed with Version 2.4.7
